from datetime import date
from pathlib import Path

import pandas as pd

from mix.sentiment_gemma.sentiment_backtest import build_backtest, build_qs_report, build_report, index_by_date


def test_index_by_date_uses_next_body():
    df = pd.DataFrame(
        [
            {"source_date": date(2026, 4, 20), "sentiment": 3, "next_body": 10.0},
            {"source_date": date(2026, 4, 21), "sentiment": -2, "next_body": -4.0},
        ]
    )

    indexed = index_by_date(df)

    assert list(indexed.columns) == ["sentiment", "next_body"]


def test_build_backtest_uses_next_body_for_follow_and_invert():
    aggregated = pd.DataFrame(
        [
            {"source_date": date(2026, 4, 20), "sentiment": 3, "next_body": 5.0},
            {"source_date": date(2026, 4, 21), "sentiment": -4, "next_body": -7.0},
        ]
    ).set_index("source_date")
    rules = [
        {"min": 3, "max": 3, "action": "follow"},
        {"min": -4, "max": -4, "action": "invert"},
    ]

    result = build_backtest(aggregated, quantity=2, rules=rules)

    assert result["direction"].tolist() == ["LONG", "LONG"]
    assert result["next_body"].tolist() == [5.0, -7.0]
    assert result["pnl"].tolist() == [10.0, -14.0]


def test_build_qs_report_replaces_quantstats_browser_title(tmp_path, monkeypatch):
    result = pd.DataFrame(
        [
            {"source_date": date(2026, 4, 20), "pnl": 10.0},
            {"source_date": date(2026, 4, 21), "pnl": -5.0},
        ]
    )
    output_html = tmp_path / "sentiment_backtest_qs.html"

    def fake_quantstats_html(returns, benchmark, output, title):
        Path(output).write_text(
            "<html><head><title>Tearsheet (generated by QuantStats)</title></head>"
            f"<body><h1>{title}</h1></body></html>",
            encoding="utf-8",
        )

    monkeypatch.setattr(
        "mix.sentiment_gemma.sentiment_backtest.qs.reports.html",
        fake_quantstats_html,
    )

    build_qs_report(result, "MIX", "gemma3:12b", output_html)

    html = output_html.read_text(encoding="utf-8")
    assert "<title>MIX | gemma3:12b | sentiment backtest (QuantStats)</title>" in html
    assert "Tearsheet (generated by QuantStats)" not in html


def test_build_report_shows_test_period_from_result_dates(tmp_path):
    result = pd.DataFrame(
        [
            {"source_date": date(2026, 4, 22), "sentiment": 1, "action": "follow", "pnl": 15.0},
            {"source_date": date(2026, 4, 20), "sentiment": -1, "action": "invert", "pnl": -5.0},
            {"source_date": date(2026, 4, 21), "sentiment": 2, "action": "follow", "pnl": 10.0},
        ]
    )
    output_html = tmp_path / "sentiment_backtest.html"

    build_report(result, "MIX", "gemma3:12b", output_html, tmp_path / "rules.yaml")

    html = output_html.read_text(encoding="utf-8")
    assert "Период тестирования: 2026-04-20 - 2026-04-22" in html


def test_build_report_reserves_space_for_three_line_title(tmp_path):
    result = pd.DataFrame(
        [
            {"source_date": date(2026, 4, 20), "sentiment": -1, "action": "invert", "pnl": -5.0},
            {"source_date": date(2026, 4, 21), "sentiment": 2, "action": "follow", "pnl": 10.0},
        ]
    )
    output_html = tmp_path / "sentiment_backtest.html"

    build_report(result, "MIX", "gemma3:12b", output_html, tmp_path / "rules.yaml")

    html = output_html.read_text(encoding="utf-8")
    assert '"margin":{"t":140}' in html
